/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as OlapReportPageIdImport } from './routes/olapReport.$pageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OlapReportPageIdRoute = OlapReportPageIdImport.update({
  id: '/olapReport/$pageId',
  path: '/olapReport/$pageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/olapReport/$pageId': {
      id: '/olapReport/$pageId'
      path: '/olapReport/$pageId'
      fullPath: '/olapReport/$pageId'
      preLoaderRoute: typeof OlapReportPageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/olapReport/$pageId': typeof OlapReportPageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/olapReport/$pageId': typeof OlapReportPageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/olapReport/$pageId': typeof OlapReportPageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/olapReport/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/olapReport/$pageId'
  id: '__root__' | '/' | '/olapReport/$pageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OlapReportPageIdRoute: typeof OlapReportPageIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OlapReportPageIdRoute: OlapReportPageIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/olapReport/$pageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/olapReport/$pageId": {
      "filePath": "olapReport.$pageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
